In [1]:
import pandas as pd

In [2]:
otu_id = pd.read_csv("belly_button_biodiversity_otu_id.csv")
otu_id.head()

   otu_id                        lowest_taxonomic_unit_found
0       1  Archaea;Euryarchaeota;Halobacteria;Halobacteri...
1       2  Archaea;Euryarchaeota;Halobacteria;Halobacteri...
2       3  Archaea;Euryarchaeota;Halobacteria;Halobacteri...
3       4  Archaea;Euryarchaeota;Methanobacteria;Methanob...
4       5  Archaea;Euryarchaeota;Methanobacteria;Methanob...

In [4]:
samples = pd.read_csv("belly_button_biodiversity_samples.csv")
samples.head()

,otu_id,BB_940,BB_941,BB_943,BB_944,BB_945,BB_946,BB_947,BB_948,BB_949,...,BB_1562,BB_1563,BB_1564,BB_1572,BB_1573,BB_1574,BB_1576,BB_1577,BB_1581,BB_1601
0,1,0.0,0,0,0,0,0,0,0.0,0,...,0,0,0,0,0,0,0,0,0,0
1,2,0.0,0,0,0,0,0,0,0.0,0,...,0,0,0,0,0,0,0,0,0,0
2,3,0.0,0,0,0,0,0,0,0.0,0,...,0,0,0,0,0,0,0,0,0,0
3,4,0.0,0,0,0,0,0,0,0.0,0,...,0,0,0,0,0,0,0,0,0,0
4,5,0.0,0,0,0,0,0,0,0.0,0,...,0,0,0,0,0,0,0,0,0,0

In [25]:
samples.set_index(["otu_id"],drop=True,inplace=True)
samples.head()

,BB_940,BB_941,BB_943,BB_944,BB_945,BB_946,BB_947,BB_948,BB_949,BB_950,...,BB_1562,BB_1563,BB_1564,BB_1572,BB_1573,BB_1574,BB_1576,BB_1577,BB_1581,BB_1601
otu_id,,,,,,,,,,,,,,,,,,,,,
1,0.0,0,0,0,0,0,0,0.0,0,0.0,...,0,0,0,0,0,0,0,0,0,0
2,0.0,0,0,0,0,0,0,0.0,0,0.0,...,0,0,0,0,0,0,0,0,0,0
3,0.0,0,0,0,0,0,0,0.0,0,0.0,...,0,0,0,0,0,0,0,0,0,0
4,0.0,0,0,0,0,0,0,0.0,0,0.0,...,0,0,0,0,0,0,0,0,0,0
5,0.0,0,0,0,0,0,0,0.0,0,0.0,...,0,0,0,0,0,0,0,0,0,0

In [28]:
samples_t.head()

otu_id,1,2,3,4,5,6,7,8,9,10,...,3665,3666,3667,3668,3669,3670,3671,3672,3673,3674
BB_940,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
BB_941,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
BB_943,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
BB_944,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
BB_945,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [29]:
samples_t.index.names=["sample"]
samples_t.head()

otu_id,1,2,3,4,5,6,7,8,9,10,...,3665,3666,3667,3668,3669,3670,3671,3672,3673,3674
sample,,,,,,,,,,,,,,,,,,,,,
BB_940,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
BB_941,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
BB_943,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
BB_944,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
BB_945,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [5]:
metadata = pd.read_csv("Belly_Button_Biodiversity_Metadata.csv")
metadata.head()

,SAMPLEID,EVENT,ETHNICITY,GENDER,AGE,WFREQ,BBTYPE,LOCATION,COUNTRY012,ZIP012,...,DOG,CAT,IMPSURFACE013,NPP013,MMAXTEMP013,PFC013,IMPSURFACE1319,NPP1319,MMAXTEMP1319,PFC1319
0,940,BellyButtonsScienceOnline,Caucasian,F,24.0,2.0,I,Beaufort/NC,usa,22306,...,no,no,8852.0,37.172222,54.5,NaN,1,NaN,33.990002,25.5
1,941,NaN,Caucasian/Midleastern,F,34.0,1.0,I,Chicago/IL,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,943,BellyButtonsScienceOnline,Caucasian,F,49.0,1.0,I,Omaha/NE,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,944,BellyButtonsScienceOnline,European,M,44.0,1.0,I,NewHaven/CT,usa,7079,...,no,yes,NaN,35.816666,16.0,NaN,0,6567.0,32.403332,28.5
4,945,BellyButtonsScienceOnline,Caucasian,F,48.0,1.0,I,Philidelphia/PA,usa,84404,...,no,no,NaN,37.783333,4.0,NaN,0,5613.0,33.634445,24.0

In [6]:
metadata.columns

Index(['SAMPLEID', 'EVENT', 'ETHNICITY', 'GENDER', 'AGE', 'WFREQ', 'BBTYPE',
       'LOCATION', 'COUNTRY012', 'ZIP012', 'COUNTRY1319', 'ZIP1319', 'DOG',
       'CAT', 'IMPSURFACE013', 'NPP013', 'MMAXTEMP013', 'PFC013',
       'IMPSURFACE1319', 'NPP1319', 'MMAXTEMP1319', 'PFC1319'],
      dtype='object')

In [7]:
metadata = metadata[['SAMPLEID', 'ETHNICITY', 'GENDER', 'AGE', 'WFREQ', 'BBTYPE',
       'LOCATION']]
metadata.head()

   SAMPLEID              ETHNICITY GENDER   AGE  WFREQ BBTYPE         LOCATION
0       940              Caucasian      F  24.0    2.0      I      Beaufort/NC
1       941  Caucasian/Midleastern      F  34.0    1.0      I       Chicago/IL
2       943              Caucasian      F  49.0    1.0      I         Omaha/NE
3       944               European      M  44.0    1.0      I      NewHaven/CT
4       945              Caucasian      F  48.0    1.0      I  Philidelphia/PA

In [10]:
metadata.SAMPLEID = metadata.SAMPLEID.astype(str)
metadata.dtypes

SAMPLEID      object
ETHNICITY     object
GENDER        object
AGE          float64
WFREQ        float64
BBTYPE        object
LOCATION      object
dtype: object

In [12]:
metadata['SAMPLEID'] = 'BB_' + metadata['SAMPLEID']
metadata.head()

  SAMPLEID              ETHNICITY GENDER   AGE  WFREQ BBTYPE         LOCATION
0   BB_940              Caucasian      F  24.0    2.0      I      Beaufort/NC
1   BB_941  Caucasian/Midleastern      F  34.0    1.0      I       Chicago/IL
2   BB_943              Caucasian      F  49.0    1.0      I         Omaha/NE
3   BB_944               European      M  44.0    1.0      I      NewHaven/CT
4   BB_945              Caucasian      F  48.0    1.0      I  Philidelphia/PA

In [13]:
otu_id.to_csv("otu_clean.csv",index=False)
samples.to_csv("samples_clean.csv",index=False)
metadata.to_csv("metadata_clean.csv",index=False)

In [14]:
import sqlalchemy
from sqlalchemy import create_engine, MetaData
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy import Column, Integer, String, Numeric, Text, Float

In [15]:
engine = create_engine("sqlite:///belly_button_biodiversity.sqlite")
conn = engine.connect()

In [16]:
Base = declarative_base()

class OTU(Base):
    __tablename__ = 'taxonomic_units'

    otu_id = Column(Integer, primary_key=True)
    lowest_taxonomic_unit_found = Column(Text)
    
    def __repr__(self):
        return f"ID: {self.otu_id}, NAME: {self.lowest_taxonomic_unit_found}"

In [17]:
Base.metadata.create_all(engine)

In [18]:
to_insert = pd.read_csv("otu_clean.csv")
data = to_insert.to_dict(orient="records")

In [19]:
data

[{'lowest_taxonomic_unit_found': 'Archaea;Euryarchaeota;Halobacteria;Halobacteriales;Halobacteriaceae;Halococcus',
  'otu_id': 1},
 {'lowest_taxonomic_unit_found': 'Archaea;Euryarchaeota;Halobacteria;Halobacteriales;Halobacteriaceae;Halococcus',
  'otu_id': 2},
 {'lowest_taxonomic_unit_found': 'Archaea;Euryarchaeota;Halobacteria;Halobacteriales;Halobacteriaceae;Natronorubrum',
  'otu_id': 3},
 {'lowest_taxonomic_unit_found': 'Archaea;Euryarchaeota;Methanobacteria;Methanobacteriales;Methanobacteriaceae;Methanobrevibacter',
  'otu_id': 4},
 {'lowest_taxonomic_unit_found': 'Archaea;Euryarchaeota;Methanobacteria;Methanobacteriales;Methanobacteriaceae;Methanobrevibacter',
  'otu_id': 5},
 {'lowest_taxonomic_unit_found': 'Archaea;Euryarchaeota;Methanobacteria;Methanobacteriales;Methanobacteriaceae;Methanobrevibacter',
  'otu_id': 6},
 {'lowest_taxonomic_unit_found': 'Bacteria', 'otu_id': 7},
 {'lowest_taxonomic_unit_found': 'Bacteria', 'otu_id': 8},
 {'lowest_taxonomic_unit_found': 'Bacteria', 'otu_id': 9},
 {'lowest_taxonomic_unit_found': 'Bacteria', 'otu_id': 10},
 {'lowest_taxonomic_unit_found': 'Bacteria', 'otu_id': 11},
 {'lowest_taxonomic_unit_found': 'Bacteria', 'otu_id': 12},
 {'lowest_taxonomic_unit_found': 'Bacteria', 'otu_id': 13},
 {'lowest_taxonomic_unit_found': 'Bacteria', 'otu_id': 14},
 {'lowest_taxonomic_unit_found': 'Bacteria', 'otu_id': 15},
 {'lowest_taxonomic_unit_found': 'Bacteria', 'otu_id': 16},
 {'lowest_taxonomic_unit_found': 'Bacteria', 'otu_id': 17},
 {'lowest_taxonomic_unit_found': 'Bacteria', 'otu_id': 18},
 {'lowest_taxonomic_unit_found': 'Bacteria', 'otu_id': 19},
 {'lowest_taxonomic_unit_found': 'Bacteria', 'otu_id': 20},
 {'lowest_taxonomic_unit_found': 'Bacteria', 'otu_id': 21},
 {'lowest_taxonomic_unit_found': 'Bacteria', 'otu_id': 22},
 {'lowest_taxonomic_unit_found': 'Bacteria', 'otu_id': 23},
 {'lowest_taxonomic_unit_found': 'Bacteria', 'otu_id': 24},
 {'lowest_taxonomic_unit_found': 'Bacteria', 'otu_id': 25},
 {'lowest_taxonomic_unit_found': 'Bacteria', 'otu_id': 26},
 {'lowest_taxonomic_unit_found': 'Bacteria', 'otu_id': 27},
 {'lowest_taxonomic_unit_found': 'Bacteria', 'otu_id': 28},
 {'lowest_taxonomic_unit_found': 'Bacteria', 'otu_id': 29},
 {'lowest_taxonomic_unit_found': 'Bacteria', 'otu_id': 30},
 {'lowest_taxonomic_unit_found': 'Bacteria', 'otu_id': 31},
 {'lowest_taxonomic_unit_found': 'Bacteria', 'otu_id': 32},
 {'lowest_taxonomic_unit_found': 'Bacteria', 'otu_id': 33},
 {'lowest_taxonomic_unit_found': 'Bacteria', 'otu_id': 34},
 {'lowest_taxonomic_unit_found': 'Bacteria', 'otu_id': 35},
 {'lowest_taxonomic_unit_found': 'Bacteria', 'otu_id': 36},
 {'lowest_taxonomic_unit_found': 'Bacteria', 'otu_id': 37},
 {'lowest_taxonomic_unit_found': 'Bacteria', 'otu_id': 38},
 {'lowest_taxonomic_unit_found': 'Bacteria', 'otu_id': 39},
 {'lowest_taxonomic_unit_found': 'Bacteria', 'otu_id': 40},
 {'lowest_taxonomic_unit_found': 'Bacteria', 'otu_id': 41},
 {'lowest_taxonomic_unit_found': 'Bacteria', 'otu_id': 42},
 {'lowest_taxonomic_unit_found': 'Bacteria', 'otu_id': 43},
 {'lowest_taxonomic_unit_found': 'Bacteria', 'otu_id': 44},
 {'lowest_taxonomic_unit_found': 'Bacteria', 'otu_id': 45},
 {'lowest_taxonomic_unit_found': 'Bacteria', 'otu_id': 46},
 {'lowest_taxonomic_unit_found': 'Bacteria', 'otu_id': 47},
 {'lowest_taxonomic_unit_found': 'Bacteria', 'otu_id': 48},
 {'lowest_taxonomic_unit_found': 'Bacteria', 'otu_id': 49},
 {'lowest_taxonomic_unit_found': 'Bacteria', 'otu_id': 50},
 {'lowest_taxonomic_unit_found': 'Bacteria', 'otu_id': 51},
 {'lowest_taxonomic_unit_found': 'Bacteria', 'otu_id': 52},
 {'lowest_taxonomic_unit_found': 'Bacteria', 'otu_id': 53},
 {'lowest_taxonomic_unit_found': 'Bacteria', 'otu_id': 54},
 {'lowest_taxonomic_unit_found': 'Bacteria', 'otu_id': 55},
 {'lowest_taxonomic_unit_found': 'Bacteria', 'otu_id': 56},
 {'lowest_taxonomic_unit_found': 'Bacteria', 'otu_id': 57},
 {'lowest_taxonomic_unit_found': 'Bacteria', 'otu_id': 58},
 {'lowest_taxonomic_unit_found': 'Bacteria', 'otu_id': 59},
 {'lowest_taxonomic_unit_found': 'Bacteria', 'otu_id': 60},
 {'lowest_taxonomic_unit_found': 'Bacteria', 'otu_id': 61},
 {'lowest_taxonomic_unit_found': 'Bacteria', 'otu_id': 62},
 {'lowest_taxonomic_unit_found': 'Bacteria', 'otu_id': 63},
 {'lowest_taxonomic_unit_found': 'Bacteria', 'otu_id': 64},
 {'lowest_taxonomic_unit_found': 'Bacteria', 'otu_id': 65},
 {'lowest_taxonomic_unit_found': 'Bacteria', 'otu_id': 66},
 {'lowest_taxonomic_unit_found': 'Bacteria', 'otu_id': 67},
 {'lowest_taxonomic_unit_found': 'Bacteria', 'otu_id': 68},
 {'lowest_taxonomic_unit_found': 'Bacteria', 'otu_id': 69},
 {'lowest_taxonomic_unit_found': 'Bacteria', 'otu_id': 70},
 {'lowest_taxonomic_unit_found': 'Bacteria', 'otu_id': 71},
 {'lowest_taxonomic_unit_found': 'Bacteria', 'otu_id': 72},
 {'lowest_taxonomic_unit_found': 'Bacteria', 'otu_id': 73},
 {'lowest_taxonomic_unit_found': 'Bacteria', 'otu_id': 74},
 {'lowest_taxonomic_unit_found': 'Bacteria', 'otu_id': 75},
 {'lowest_taxonomic_unit_found': 'Bacteria', 'otu_id': 76},
 {'lowest_taxonomic_unit_found': 'Bacteria', 'otu_id': 77},
 {'lowest_taxonomic_unit_found': 'Bacteria', 'otu_id': 78},
 {'lowest_taxonomic_unit_found': 'Bacteria', 'otu_id': 79},
 {'lowest_taxonomic_unit_found': 'Bacteria', 'otu_id': 80},
 {'lowest_taxonomic_unit_found': 'Bacteria', 'otu_id': 81},
 {'lowest_taxonomic_unit_found': 'Bacteria', 'otu_id': 82},
 {'lowest_taxonomic_unit_found': 'Bacteria', 'otu_id': 83},
 {'lowest_taxonomic_unit_found': 'Bacteria', 'otu_id': 84},
 {'lowest_taxonomic_unit_found': 'Bacteria', 'otu_id': 85},
 {'lowest_taxonomic_unit_found': 'Bacteria', 'otu_id': 86},
 {'lowest_taxonomic_unit_found': 'Bacteria', 'otu_id': 87},
 {'lowest_taxonomic_unit_found': 'Bacteria', 'otu_id': 88},
 {'lowest_taxonomic_unit_found': 'Bacteria', 'otu_id': 89},
 {'lowest_taxonomic_unit_found': 'Bacteria', 'otu_id': 90},
 {'lowest_taxonomic_unit_found': 'Bacteria', 'otu_id': 91},
 {'lowest_taxonomic_unit_found': 'Bacteria', 'otu_id': 92},
 {'lowest_taxonomic_unit_found': 'Bacteria', 'otu_id': 93},
 {'lowest_taxonomic_unit_found': 'Bacteria', 'otu_id': 94},
 {'lowest_taxonomic_unit_found': 'Bacteria', 'otu_id': 95},
 {'lowest_taxonomic_unit_found': 'Bacteria', 'otu_id': 96},
 {'lowest_taxonomic_unit_found': 'Bacteria', 'otu_id': 97},
 {'lowest_taxonomic_unit_found': 'Bacteria', 'otu_id': 98},
 {'lowest_taxonomic_unit_found': 'Bacteria', 'otu_id': 99},
 {'lowest_taxonomic_unit_found': 'Bacteria', 'otu_id': 100},
 {'lowest_taxonomic_unit_found': 'Bacteria', 'otu_id': 101},
 {'lowest_taxonomic_unit_found': 'Bacteria', 'otu_id': 102},
 {'lowest_taxonomic_unit_found': 'Bacteria', 'otu_id': 103},
 {'lowest_taxonomic_unit_found': 'Bacteria', 'otu_id': 104},
 {'lowest_taxonomic_unit_found': 'Bacteria', 'otu_id': 105},
 {'lowest_taxonomic_unit_found': 'Bacteria', 'otu_id': 106},
 {'lowest_taxonomic_unit_found': 'Bacteria', 'otu_id': 107},
 {'lowest_taxonomic_unit_found': 'Bacteria', 'otu_id': 108},
 {'lowest_taxonomic_unit_found': 'Bacteria', 'otu_id': 109},
 {'lowest_taxonomic_unit_found': 'Bacteria', 'otu_id': 110},
 {'lowest_taxonomic_unit_found': 'Bacteria', 'otu_id': 111},
 {'lowest_taxonomic_unit_found': 'Bacteria', 'otu_id': 112},
 {'lowest_taxonomic_unit_found': 'Bacteria', 'otu_id': 113},
 {'lowest_taxonomic_unit_found': 'Bacteria', 'otu_id': 114},
 {'lowest_taxonomic_unit_found': 'Bacteria', 'otu_id': 115},
 {'lowest_taxonomic_unit_found': 'Bacteria', 'otu_id': 116},
 {'lowest_taxonomic_unit_found': 'Bacteria', 'otu_id': 117},
 {'lowest_taxonomic_unit_found': 'Bacteria', 'otu_id': 118},
 {'lowest_taxonomic_unit_found': 'Bacteria', 'otu_id': 119},
 {'lowest_taxonomic_unit_found': 'Bacteria', 'otu_id': 120},
 {'lowest_taxonomic_unit_found': 'Bacteria', 'otu_id': 121},
 {'lowest_taxonomic_unit_found': 'Bacteria', 'otu_id': 122},
 {'lowest_taxonomic_unit_found': 'Bacteria', 'otu_id': 123},
 {'lowest_taxonomic_unit_found': 'Bacteria', 'otu_id': 124},
 {'lowest_taxonomic_unit_found': 'Bacteria', 'otu_id': 125},
 {'lowest_taxonomic_unit_found': 'Bacteria', 'otu_id': 126},
 {'lowest_taxonomic_unit_found': 'Bacteria', 'otu_id': 127},
 {'lowest_taxonomic_unit_found': 'Bacteria', 'otu_id': 128},
 {'lowest_taxonomic_unit_found': 'Bacteria', 'otu_id': 129},
 {'lowest_taxonomic_unit_found': 'Bacteria', 'otu_id': 130},
 {'lowest_taxonomic_unit_found': 'Bacteria', 'otu_id': 131},
 {'lowest_taxonomic_unit_found': 'Bacteria', 'otu_id': 132},
 {'lowest_taxonomic_unit_found': 'Bacteria', 'otu_id': 133},
 {'lowest_taxonomic_unit_found': 'Bacteria', 'otu_id': 134},
 {'lowest_taxonomic_unit_found': 'Bacteria', 'otu_id': 135},
 {'lowest_taxonomic_unit_found': 'Bacteria', 'otu_id': 136},
 {'lowest_taxonomic_unit_found': 'Bacteria', 'otu_id': 137},
 {'lowest_taxonomic_unit_found': 'Bacteria', 'otu_id': 138},
 {'lowest_taxonomic_unit_found': 'Bacteria', 'otu_id': 139},
 {'lowest_taxonomic_unit_found': 'Bacteria', 'otu_id': 140},
 {'lowest_taxonomic_unit_found': 'Bacteria', 'otu_id': 141},
 {'lowest_taxonomic_unit_found': 'Bacteria', 'otu_id': 142},
 {'lowest_taxonomic_unit_found': 'Bacteria', 'otu_id': 143},
 {'lowest_taxonomic_unit_found': 'Bacteria', 'otu_id': 144},
 {'lowest_taxonomic_unit_found': 'Bacteria', 'otu_id': 145},
 {'lowest_taxonomic_unit_found': 'Bacteria', 'otu_id': 146},
 {'lowest_taxonomic_unit_found': 'Bacteria', 'otu_id': 147},
 {'lowest_taxonomic_unit_found': 'Bacteria', 'otu_id': 148},
 {'lowest_taxonomic_unit_found': 'Bacteria', 'otu_id': 149},
 {'lowest_taxonomic_unit_found': 'Bacteria', 'otu_id': 150},
 {'lowest_taxonomic_unit_found': 'Bacteria', 'otu_id': 151},
 {'lowest_taxonomic_unit_found': 'Bacteria', 'otu_id': 152},
 {'lowest_taxonomic_unit_found': 'Bacteria', 'otu_id': 153},
 {'lowest_taxonomic_unit_found': 'Bacteria', 'otu_id': 154},
 {'lowest_taxonomic_unit_found': 'Bacteria', 'otu_id': 155},
 {'lowest_taxonomic_unit_found': 'Bacteria', 'otu_id': 156},
 {'lowest_taxonomic_unit_found': 'Bacteria', 'otu_id': 157},
 {'lowest_taxonomic_unit_found': 'Bacteria', 'otu_id': 158},
 {'lowest_taxonomic_unit_found': 'Bacteria', 'otu_id': 159},
 {'lowest_taxonomic_unit_found': 'Bacteria', 'otu_id': 160},
 {'lowest_taxonomic_unit_found': 'Bacteria', 'otu_id': 161},
 {'lowest_taxonomic_unit_found': 'Bacteria', 'otu_id': 162},
 {'lowest_taxonomic_unit_found': 'Bacteria', 'otu_id': 163},
 {'lowest_taxonomic_unit_found': 'Bacteria', 'otu_id': 164},
 {'lowest_taxonomic_unit_found': 'Bacteria', 'otu_id': 165},
 {'lowest_taxonomic_unit_found': 'Bacteria', 'otu_id': 166},
 {'lowest_taxonomic_unit_found': 'Bacteria', 'otu_id': 167},
 {'lowest_taxonomic_unit_found': 'Bacteria', 'otu_id': 168},
 {'lowest_taxonomic_unit_found': 'Bacteria', 'otu_id': 169},
 {'lowest_taxonomic_unit_found': 'Bacteria', 'otu_id': 170},
 {'lowest_taxonomic_unit_found': 'Bacteria', 'otu_id': 171},
 {'lowest_taxonomic_unit_found': 'Bacteria', 'otu_id': 172},
 {'lowest_taxonomic_unit_found': 'Bacteria', 'otu_id': 173},
 {'lowest_taxonomic_unit_found': 'Bacteria', 'otu_id': 174},
 {'lowest_taxonomic_unit_found': 'Bacteria', 'otu_id': 175},
 {'lowest_taxonomic_unit_found': 'Bacteria', 'otu_id': 176},
 {'lowest_taxonomic_unit_found': 'Bacteria', 'otu_id': 177},
 {'lowest_taxonomic_unit_found': 'Bacteria', 'otu_id': 178},
 {'lowest_taxonomic_unit_found': 'Bacteria', 'otu_id': 179},
 {'lowest_taxonomic_unit_found': 'Bacteria', 'otu_id': 180},
 {'lowest_taxonomic_unit_found': 'Bacteria', 'otu_id': 181},
 {'lowest_taxonomic_unit_found': 'Bacteria', 'otu_id': 182},
 {'lowest_taxonomic_unit_found': 'Bacteria', 'otu_id': 183},
 {'lowest_taxonomic_unit_found': 'Bacteria', 'otu_id': 184},
 {'lowest_taxonomic_unit_found': 'Bacteria', 'otu_id': 185},
 {'lowest_taxonomic_unit_found': 'Bacteria', 'otu_id': 186},
 {'lowest_taxonomic_unit_found': 'Bacteria', 'otu_id': 187},
 {'lowest_taxonomic_unit_found': 'Bacteria', 'otu_id': 188},
 {'lowest_taxonomic_unit_found': 'Bacteria', 'otu_id': 189},
 {'lowest_taxonomic_unit_found': 'Bacteria', 'otu_id': 190},
 {'lowest_taxonomic_unit_found': 'Bacteria', 'otu_id': 191},
 {'lowest_taxonomic_unit_found': 'Bacteria', 'otu_id': 192},
 {'lowest_taxonomic_unit_found': 'Bacteria', 'otu_id': 193},
 {'lowest_taxonomic_unit_found': 'Bacteria', 'otu_id': 194},
 {'lowest_taxonomic_unit_found': 'Bacteria', 'otu_id': 195},
 {'lowest_taxonomic_unit_found': 'Bacteria', 'otu_id': 196},
 {'lowest_taxonomic_unit_found': 'Bacteria', 'otu_id': 197},
 {'lowest_taxonomic_unit_found': 'Bacteria', 'otu_id': 198},
 {'lowest_taxonomic_unit_found': 'Bacteria', 'otu_id': 199},
 {'lowest_taxonomic_unit_found': 'Bacteria', 'otu_id': 200},
 {'lowest_taxonomic_unit_found': 'Bacteria', 'otu_id': 201},
 {'lowest_taxonomic_unit_found': 'Bacteria', 'otu_id': 202},
 {'lowest_taxonomic_unit_found': 'Bacteria', 'otu_id': 203},
 {'lowest_taxonomic_unit_found': 'Bacteria', 'otu_id': 204},
 {'lowest_taxonomic_unit_found': 'Bacteria', 'otu_id': 205},
 {'lowest_taxonomic_unit_found': 'Bacteria', 'otu_id': 206},
 {'lowest_taxonomic_unit_found': 'Bacteria', 'otu_id': 207},
 {'lowest_taxonomic_unit_found': 'Bacteria', 'otu_id': 208},
 {'lowest_taxonomic_unit_found': 'Bacteria', 'otu_id': 209},
 {'lowest_taxonomic_unit_found': 'Bacteria', 'otu_id': 210},
 {'lowest_taxonomic_unit_found': 'Bacteria', 'otu_id': 211},
 {'lowest_taxonomic_unit_found': 'Bacteria', 'otu_id': 212},
 {'lowest_taxonomic_unit_found': 'Bacteria', 'otu_id': 213},
 {'lowest_taxonomic_unit_found': 'Bacteria', 'otu_id': 214},
 {'lowest_taxonomic_unit_found': 'Bacteria', 'otu_id': 215},
 {'lowest_taxonomic_unit_found': 'Bacteria', 'otu_id': 216},
 {'lowest_taxonomic_unit_found': 'Bacteria', 'otu_id': 217},
 {'lowest_taxonomic_unit_found': 'Bacteria', 'otu_id': 218},
 {'lowest_taxonomic_unit_found': 'Bacteria', 'otu_id': 219},
 {'lowest_taxonomic_unit_found': 'Bacteria', 'otu_id': 220},
 {'lowest_taxonomic_unit_found': 'Bacteria', 'otu_id': 221},
 {'lowest_taxonomic_unit_found': 'Bacteria', 'otu_id': 222},
 {'lowest_taxonomic_unit_found': 'Bacteria', 'otu_id': 223},
 {'lowest_taxonomic_unit_found': 'Bacteria', 'otu_id': 224},
 {'lowest_taxonomic_unit_found': 'Bacteria', 'otu_id': 225},
 {'lowest_taxonomic_unit_found': 'Bacteria', 'otu_id': 226},
 {'lowest_taxonomic_unit_found': 'Bacteria', 'otu_id': 227},
 {'lowest_taxonomic_unit_found': 'Bacteria', 'otu_id': 228},
 {'lowest_taxonomic_unit_found': 'Bacteria', 'otu_id': 229},
 {'lowest_taxonomic_unit_found': 'Bacteria', 'otu_id': 230},
 {'lowest_taxonomic_unit_found': 'Bacteria', 'otu_id': 231},
 {'lowest_taxonomic_unit_found': 'Bacteria', 'otu_id': 232},
 {'lowest_taxonomic_unit_found': 'Bacteria', 'otu_id': 233},
 {'lowest_taxonomic_unit_found': 'Bacteria', 'otu_id': 234},
 {'lowest_taxonomic_unit_found': 'Bacteria', 'otu_id': 235},
 {'lowest_taxonomic_unit_found': 'Bacteria', 'otu_id': 236},
 {'lowest_taxonomic_unit_found': 'Bacteria', 'otu_id': 237},
 {'lowest_taxonomic_unit_found': 'Bacteria', 'otu_id': 238},
 {'lowest_taxonomic_unit_found': 'Bacteria', 'otu_id': 239},
 {'lowest_taxonomic_unit_found': 'Bacteria', 'otu_id': 240},
 {'lowest_taxonomic_unit_found': 'Bacteria', 'otu_id': 241},
 {'lowest_taxonomic_unit_found': 'Bacteria', 'otu_id': 242},
 {'lowest_taxonomic_unit_found': 'Bacteria', 'otu_id': 243},
 {'lowest_taxonomic_unit_found': 'Bacteria', 'otu_id': 244},
 {'lowest_taxonomic_unit_found': 'Bacteria', 'otu_id': 245},
 {'lowest_taxonomic_unit_found': 'Bacteria', 'otu_id': 246},
 {'lowest_taxonomic_unit_found': 'Bacteria', 'otu_id': 247},
 {'lowest_taxonomic_unit_found': 'Bacteria', 'otu_id': 248},
 {'lowest_taxonomic_unit_found': 'Bacteria', 'otu_id': 249},
 {'lowest_taxonomic_unit_found': 'Bacteria', 'otu_id': 250},
 {'lowest_taxonomic_unit_found': 'Bacteria', 'otu_id': 251},
 {'lowest_taxonomic_unit_found': 'Bacteria', 'otu_id': 252},
 {'lowest_taxonomic_unit_found': 'Bacteria', 'otu_id': 253},
 {'lowest_taxonomic_unit_found': 'Bacteria', 'otu_id': 254},
 {'lowest_taxonomic_unit_found': 'Bacteria', 'otu_id': 255},
 {'lowest_taxonomic_unit_found': 'Bacteria', 'otu_id': 256},
 {'lowest_taxonomic_unit_found': 'Bacteria', 'otu_id': 257},
 {'lowest_taxonomic_unit_found': 'Bacteria', 'otu_id': 258},
 {'lowest_taxonomic_unit_found': 'Bacteria', 'otu_id': 259},
 {'lowest_taxonomic_unit_found': 'Bacteria', 'otu_id': 260},
 {'lowest_taxonomic_unit_found': 'Bacteria', 'otu_id': 261},
 {'lowest_taxonomic_unit_found': 'Bacteria', 'otu_id': 262},
 {'lowest_taxonomic_unit_found': 'Bacteria', 'otu_id': 263},
 {'lowest_taxonomic_unit_found': 'Bacteria', 'otu_id': 264},
 {'lowest_taxonomic_unit_found': 'Bacteria', 'otu_id': 265},
 {'lowest_taxonomic_unit_found': 'Bacteria', 'otu_id': 266},
 {'lowest_taxonomic_unit_found': 'Bacteria', 'otu_id': 267},
 {'lowest_taxonomic_unit_found': 'Bacteria', 'otu_id': 268},
 {'lowest_taxonomic_unit_found': 'Bacteria', 'otu_id': 269},
 {'lowest_taxonomic_unit_found': 'Bacteria', 'otu_id': 270},
 {'lowest_taxonomic_unit_found': 'Bacteria', 'otu_id': 271},
 {'lowest_taxonomic_unit_found': 'Bacteria', 'otu_id': 272},
 {'lowest_taxonomic_unit_found': 'Bacteria', 'otu_id': 273},
 {'lowest_taxonomic_unit_found': 'Bacteria', 'otu_id': 274},
 {'lowest_taxonomic_unit_found': 'Bacteria', 'otu_id': 275},
 {'lowest_taxonomic_unit_found': 'Bacteria', 'otu_id': 276},
 {'lowest_taxonomic_unit_found': 'Bacteria', 'otu_id': 277},
 {'lowest_taxonomic_unit_found': 'Bacteria', 'otu_id': 278},
 {'lowest_taxonomic_unit_found': 'Bacteria', 'otu_id': 279},
 {'lowest_taxonomic_unit_found': 'Bacteria', 'otu_id': 280},
 {'lowest_taxonomic_unit_found': 'Bacteria', 'otu_id': 281},
 {'lowest_taxonomic_unit_found': 'Bacteria', 'otu_id': 282},
 {'lowest_taxonomic_unit_found': 'Bacteria', 'otu_id': 283},
 {'lowest_taxonomic_unit_found': 'Bacteria', 'otu_id': 284},
 {'lowest_taxonomic_unit_found': 'Bacteria', 'otu_id': 285},
 {'lowest_taxonomic_unit_found': 'Bacteria', 'otu_id': 286},
 {'lowest_taxonomic_unit_found': 'Bacteria', 'otu_id': 287},
 {'lowest_taxonomic_unit_found': 'Bacteria', 'otu_id': 288},
 {'lowest_taxonomic_unit_found': 'Bacteria', 'otu_id': 289},
 {'lowest_taxonomic_unit_found': 'Bacteria', 'otu_id': 290},
 {'lowest_taxonomic_unit_found': 'Bacteria', 'otu_id': 291},
 {'lowest_taxonomic_unit_found': 'Bacteria', 'otu_id': 292},
 {'lowest_taxonomic_unit_found': 'Bacteria', 'otu_id': 293},
 {'lowest_taxonomic_unit_found': 'Bacteria', 'otu_id': 294},
 {'lowest_taxonomic_unit_found': 'Bacteria', 'otu_id': 295},
 {'lowest_taxonomic_unit_found': 'Bacteria', 'otu_id': 296},
 {'lowest_taxonomic_unit_found': 'Bacteria', 'otu_id': 297},
 {'lowest_taxonomic_unit_found': 'Bacteria', 'otu_id': 298},
 {'lowest_taxonomic_unit_found': 'Bacteria', 'otu_id': 299},
 {'lowest_taxonomic_unit_found': 'Bacteria', 'otu_id': 300},
 {'lowest_taxonomic_unit_found': 'Bacteria', 'otu_id': 301},
 {'lowest_taxonomic_unit_found': 'Bacteria', 'otu_id': 302},
 {'lowest_taxonomic_unit_found': 'Bacteria', 'otu_id': 303},
 {'lowest_taxonomic_unit_found': 'Bacteria', 'otu_id': 304},
 {'lowest_taxonomic_unit_found': 'Bacteria', 'otu_id': 305},
 {'lowest_taxonomic_unit_found': 'Bacteria', 'otu_id': 306},
 {'lowest_taxonomic_unit_found': 'Bacteria', 'otu_id': 307},
 {'lowest_taxonomic_unit_found': 'Bacteria', 'otu_id': 308},
 {'lowest_taxonomic_unit_found': 'Bacteria', 'otu_id': 309},
 {'lowest_taxonomic_unit_found': 'Bacteria', 'otu_id': 310},
 {'lowest_taxonomic_unit_found': 'Bacteria', 'otu_id': 311},
 {'lowest_taxonomic_unit_found': 'Bacteria', 'otu_id': 312},
 {'lowest_taxonomic_unit_found': 'Bacteria', 'otu_id': 313},
 {'lowest_taxonomic_unit_found': 'Bacteria', 'otu_id': 314},
 {'lowest_taxonomic_unit_found': 'Bacteria', 'otu_id': 315},
 {'lowest_taxonomic_unit_found': 'Bacteria', 'otu_id': 316},
 {'lowest_taxonomic_unit_found': 'Bacteria', 'otu_id': 317},
 {'lowest_taxonomic_unit_found': 'Bacteria', 'otu_id': 318},
 {'lowest_taxonomic_unit_found': 'Bacteria', 'otu_id': 319},
 {'lowest_taxonomic_unit_found': 'Bacteria', 'otu_id': 320},
 {'lowest_taxonomic_unit_found': 'Bacteria', 'otu_id': 321},

In [20]:
metadata = MetaData(bind=engine)
metadata.reflect()

In [21]:
table = sqlalchemy.Table('taxonomic_units', metadata, autoload=True)

In [22]:
conn.execute(table.insert(), data)

In [23]:
conn.execute("select * from taxonomic_units limit 5").fetchall()

[(1, 'Archaea;Euryarchaeota;Halobacteria;Halobacteriales;Halobacteriaceae;Halococcus'),
 (2, 'Archaea;Euryarchaeota;Halobacteria;Halobacteriales;Halobacteriaceae;Halococcus'),
 (3, 'Archaea;Euryarchaeota;Halobacteria;Halobacteriales;Halobacteriaceae;Natronorubrum'),
 (4, 'Archaea;Euryarchaeota;Methanobacteria;Methanobacteriales;Methanobacteriaceae;Methanobrevibacter'),
 (5, 'Archaea;Euryarchaeota;Methanobacteria;Methanobacteriales;Methanobacteriaceae;Methanobrevibacter')]